### ISSUE TITLE
Error messages with pedigree chart 1.5.0

### ISSUE THREAD

**Issue by Lordrascal01** [magicsunday/webtrees-pedigree-chart#61]
**Describe the bug**
Getting error messages when trying to use the latest version of the chart

**To Reproduce**
1. upload to ftp-server
2. open my page
3. open the pedigree-chart
4. seeing errors

`Call to undefined method Fisharebest\Webtrees\Validator::attributes() …/modules_v4/webtrees-pedigree-chart/src/Module.php:138
#0 …/app/Http/Middleware/WrapHandler.php(66): MagicSunday\Webtrees\PedigreeChart\Module->handle()
#1 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()
#2 …/modules_v4/faces/src/Modules/FacesModule.php(93): Middleland\Dispatcher->handle()
#3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process()
#4 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle()
#5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#6 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle()
#7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#9 …/app/Http/Middleware/Router.php(166): Middleland\Dispatcher->dispatch()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#11 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#13 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle()
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#15 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#16 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#17 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#19 …/app/Http/Middleware/DoHousekeeping.php(74): Middleland\Dispatcher->handle()
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#21 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle()
#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#23 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#25 …/app/Http/Middleware/UseLanguage.php(70): Middleland\Dispatcher->handle()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#27 …/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher->handle()
#28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#29 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle()
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#31 …/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher->handle()
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#33 …/app/Http/Middleware/BadBotBlocker.php(223): Middleland\Dispatcher->handle()
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#35 …/app/Http/Middleware/CompressResponse.php(75): Middleland\Dispatcher->handle()
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#37 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#39 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle()
#40 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#42 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#44 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#46 …/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#48 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#50 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#52 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#53 …/app/Webtrees.php(239): Middleland\Dispatcher->dispatch()
#54 …/app/Webtrees.php(226): Fisharebest\Webtrees\Webtrees::dispatch()
#55 …/index.php(44): Fisharebest\Webtrees\Webtrees->httpRequest()
#56 {main}`

**Desktop (please complete the following information):**
 - Browser: chrome
 - Webtrees version 2.0.25
 - Version of pedigree chart 1.5.0 shows errors
 - Version of pedigree chart 1.3.1-dev works fine

**Comment by magicsunday** [comment]
If you still using webtrees 2.0.25 you have to use Version 1.3 of the module https://github.com/magicsunday/webtrees-pedigree-chart/releases/tag/1.3.0
