### ISSUE TITLE
No silhouette-X.svg available

### ISSUE THREAD

**Issue by hartenthaler** [magicsunday/webtrees-pedigree-chart#69]
The following error appears if I try to show a diagram. It is related to the fact that the person has as sex "divers/other = X". The GEDCOM test file is: 
[sozialtest.ged.txt](https://github.com/magicsunday/webtrees-pedigree-chart/files/14772538/sozialtest.ged.txt)

> filemtime> filemtime(): stat failed for …/modules_v4/webtrees-pedigree-chart/src/../resources/images/silhouette-X.svg …/app/Module/ModuleCustomTrait.php:155
> #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
> #1 …/app/Module/ModuleCustomTrait.php(155): filemtime()
> #2 …/modules_v4/webtrees-pedigree-chart/src/Processor/ImageProcessor.php(82): MagicSunday\Webtrees\PedigreeChart\Module->assetUrl()
> #3 …/modules_v4/webtrees-pedigree-chart/src/Facade/DataFacade.php(179): MagicSunday\Webtrees\PedigreeChart\Processor\ImageProcessor->getHighlightImageUrl()
> #4 …/modules_v4/webtrees-pedigree-chart/src/Facade/DataFacade.php(117): MagicSunday\Webtrees\PedigreeChart\Facade\DataFacade->getNodeData()
> #5 …/modules_v4/webtrees-pedigree-chart/src/Facade/DataFacade.php(98): MagicSunday\Webtrees\PedigreeChart\Facade\DataFacade->buildTreeStructure()
> #6 …/modules_v4/webtrees-pedigree-chart/src/Module.php(200): MagicSunday\Webtrees\PedigreeChart\Facade\DataFacade->createTreeStructure()(): stat failed for …/modules_v4/webtrees-pedigree-chart/src/../resources/images/silhouette-X.svg …/app/Module/ModuleCustomTrait.php:155
> #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
> #1 …/app/Module/ModuleCustomTrait.php(155): filemtime()
> #2 …/modules_v4/webtrees-pedigree-chart/src/Processor/ImageProcessor.php(82): MagicSunday\Webtrees\PedigreeChart\Module->assetUrl()
> #3 …/modules_v4/webtrees-pedigree-chart/src/Facade/DataFacade.php(179): MagicSunday\Webtrees\PedigreeChart\Processor\ImageProcessor->getHighlightImageUrl()
> #4 …/modules_v4/webtrees-pedigree-chart/src/Facade/DataFacade.php(117): MagicSunday\Webtrees\PedigreeChart\Facade\DataFacade->getNodeData()
> #5 …/modules_v4/webtrees-pedigree-chart/src/Facade/DataFacade.php(98): MagicSunday\Webtrees\PedigreeChart\Facade\DataFacade->buildTreeStructure()
> #6 …/modules_v4/webtrees-pedigree-chart/src/Module.php(200): MagicSunday\Webtrees\PedigreeChart\Facade\DataFacade->createTreeStructure()

**Comment by magicsunday** [comment]
@hartenthaler Should be fixed in the latest version of branch 2.1. Can you confirm that?
